---
title: "index"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary Info
To start your report, you should summarize relevant features of your dataset. Write a paragraph providing a high-level overview of shootings in the US, based on the dataset. This should provide your reader with a sense of scale of the issue, including answers to these questions:

How many shooting events occurred? 
How many lives were lost?
Which city was most impacted by shootings (make sure to clarify  how you are measuring "impact")?
Two other insights of your choice
Data in this paragraph should reference values that you calculate in R, and should not simply be typed as text into the paragraph.
## Summary Table
To show a set of quantitative values to your user, you should include a well formatted summary table of your interest. The table should be sorted in a meaningful way. This should not just be the raw data, but instead should an aggregate table of information. How you would like to aggregate the information (by city, state, month, day of the week, etc.) is up to you. Make sure to include accompanying text that describes the important insights from the table.

## Description of a particular incident
Your report will include a paragraph (4+ sentences) of in-depth information about a particular (single) incident. You should provide your reader with relevant information from the dataset, such as the date and location of the incident, as well as the number of people impacted (injured, killed). You should include a link to at least one outside resource (not found in the data). Data in this paragraph should reference values that you calculate in R, and should not simply be typed as text into the paragraph.

## An interactive map
General. While maps are not always the most appropriate visual representation of geographic data, they are extraordinarily popular and attract broad audiences. Before rendering your make, make sure to introduce the purpose of displaying the map in the report (e.g., what types of comparisons it affords).

You'll build an interactive map that shows a marker at the location of each shooting. On your map, manipulate the size of the markers based on the underlying dataset (# injured, # killed, etc.). When hovered or clicked on, each point should provide at least 3 pieces of information about the incident (with a line break -- <br> -- between each piece of information) and no irrelevant information.

Below your map, you must note at least 2 insights revealed by the map.

Important: Choice of plotting library is up to you, though I suggest you consult the interactive visualization chapter of the book -- remember, the map must be interactive.  Please see chapter 17. 

## A plot of your choice
In addition to the interactive map, you will build an additional plot of your choice to answer a specific question about your data. You can do this using the package of your choice, such as ggplot2, plotly, bokeh, or others. The choices you make should be tied directly to the question you have about your data.  We recommend that you use ggplot2. 

Similarly to your map, you should integrate your plot seamlessly with the rest of your report, and reference/describe it in your text. Regardless of library, the chart should have meaningful and clear title, axis labels, and legend (if appropriate). 

You should provide a defense of why you chose the visual encodings of the chart (i.e., you chose a layout to answer a specific question), and list at least 2 insights gained from the chart.